### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by edmBernard** [edmBernard/kilo#1]
add fonctionnality : 
- [ ] search and replace
- [ ] python highlighting
- [ ] regex for search and replace but we need C++11
- [ ] pattern highlighting
- [ ] reset terminal after leave editor
- [ ] add help/list of all command on F1
- [ ] move line
- [ ] duplicate line
- [ ] add selection 
- [ ] (un)comment block
- [ ] ctrl+left/right move cursor words
- [ ] ctrl+up/down move cursor page
